In [1]:
import pandas as pd
import numpy as np

- Write a Pandas program to build DataFrame from the following Data

    * names = ['Ahmad', 'Fatma', 'Mahmoud', 'Anas', 'Omar', 'Sayed', 'Ali', 'Maryam', 'Habiba', 'Alaa']
    * scores = [12.5, 9, 16.5, 17, 9, 20, 14.5, 10, 8, 19]
    * attempts = [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
    * qualify = ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']

In [21]:
data = { 
    'scores' : [12.5, 9, 16.5, 17, 9, 20, 14.5, 10, 8, 19],
    'attempts' : [1, 3, 2, 1, 2, 1, 3, 2, 1, 2],
    'qualify' : ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

names = ['Ahmad', 'Fatma', 'Mahmoud', 'Anas', 'Omar', 'Sayed', 'Ali', 'Maryam', 'Habiba', 'Alaa']

df = pd.DataFrame(data, index=pd.Index(names, name='Name Of Student'))
df

                 scores  attempts qualify
Name Of Student
Ahmad              12.5         1     yes
Fatma               9.0         3      no
Mahmoud            16.5         2     yes
Anas               17.0         1      no
Omar                9.0         2      no
Sayed              20.0         1     yes
Ali                14.5         3     yes
Maryam             10.0         2      no
Habiba              8.0         1      no
Alaa               19.0         2     yes

- Write a Pandas program to select the 'name' and 'score' columns from the Previous DataFrame

In [22]:
df_1 = df.reset_index()[['Name Of Student', 'scores']]
print(df_1, '\n')

df_2 = df.reset_index()
print(df_2.loc[:, ['Name Of Student', 'scores']])

  Name Of Student  scores
0           Ahmad    12.5
1           Fatma     9.0
2         Mahmoud    16.5
3            Anas    17.0
4            Omar     9.0
5           Sayed    20.0
6             Ali    14.5
7          Maryam    10.0
8          Habiba     8.0
9            Alaa    19.0

  Name Of Student  scores
0           Ahmad    12.5
1           Fatma     9.0
2         Mahmoud    16.5
3            Anas    17.0
4            Omar     9.0
5           Sayed    20.0
6             Ali    14.5
7          Maryam    10.0
8          Habiba     8.0
9            Alaa    19.0

- Write a pandas program to add 5 to `scores` column

In [23]:
df['updated_scores'] = df['scores'] + 5
df

                 scores  attempts qualify  updated_scores
Name Of Student
Ahmad              12.5         1     yes            17.5
Fatma               9.0         3      no            14.0
Mahmoud            16.5         2     yes            21.5
Anas               17.0         1      no            22.0
Omar                9.0         2      no            14.0
Sayed              20.0         1     yes            25.0
Ali                14.5         3     yes            19.5
Maryam             10.0         2      no            15.0
Habiba              8.0         1      no            13.0
Alaa               19.0         2     yes            24.0

- Write a Pandas program to show students with score > 20.

In [24]:
df[df['updated_scores'] > 20]

                 scores  attempts qualify  updated_scores
Name Of Student
Mahmoud            16.5         2     yes            21.5
Anas               17.0         1      no            22.0
Sayed              20.0         1     yes            25.0
Alaa               19.0         2     yes            24.0

- Write a Pandas program to show 'qualified' students.

In [27]:
qualified_students = (df[df['qualify'] == 'yes'])
qualified_students

                 scores  attempts qualify  updated_scores
Name Of Student
Ahmad              12.5         1     yes            17.5
Mahmoud            16.5         2     yes            21.5
Sayed              20.0         1     yes            25.0
Ali                14.5         3     yes            19.5
Alaa               19.0         2     yes            24.0

- Write a pandas program to remove the last row in the dataframe.

In [28]:
df.drop(df.index[-1], inplace=True)
df

                 scores  attempts qualify  updated_scores
Name Of Student
Ahmad              12.5         1     yes            17.5
Fatma               9.0         3      no            14.0
Mahmoud            16.5         2     yes            21.5
Anas               17.0         1      no            22.0
Omar                9.0         2      no            14.0
Sayed              20.0         1     yes            25.0
Ali                14.5         3     yes            19.5
Maryam             10.0         2      no            15.0
Habiba              8.0         1      no            13.0

- Write a pandas program to find the minimum, maximum, and range of scores.

In [29]:
min_scores = df['scores'].min()
max_scores = df['scores'].max()
range_scores = max_scores - min_scores

print(f'Min Scores= {min_scores}\nMax Scores {max_scores}\nRange Scores={range_scores}')

Min Scores= 8.0
Max Scores 20.0
Range Scores=12.0

- write pandas program to drop the `attempts` column

In [30]:
df.drop('attempts', axis= 1, inplace= True)
df

                 scores qualify  updated_scores
Name Of Student
Ahmad              12.5     yes            17.5
Fatma               9.0      no            14.0
Mahmoud            16.5     yes            21.5
Anas               17.0      no            22.0
Omar                9.0      no            14.0
Sayed              20.0     yes            25.0
Ali                14.5     yes            19.5
Maryam             10.0      no            15.0
Habiba              8.0      no            13.0

- write pandas program to save the dataframe as csv file name `my_dataframe.csv`

In [31]:
df.to_csv('my_dataframe.csv', index= False)